version: "3.7"
services:
  postgres:
    image: postgres:latest
  redis:
    image: redis:latest
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - 8080:80
  api:
    depends_on:
    - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server 
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - env.PGUSER=postgres
      - env.PGHOST=postgres
      - env.PGDATABASE=postgres
      - env.PGPASSWORD=postgres_password
      - env.PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  worker:
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
      